import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from "@google/genai";
import { 
  FileText, 
  Download, 
  Sparkles, 
  ChevronRight, 
  AlertCircle,
  CheckCircle2,
  DollarSign,
  Loader2,
  Phone,
  Smartphone,
  X,
  ClipboardCheck,
  ShieldCheck
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '../utils/cn';
import { useAuth } from '../contexts/AuthContext';

const AssessorsTool: React.FC = () => {
  const { user } = useAuth();
  const [unitTitle, setUnitTitle] = useState('');
  const [unitCode, setUnitCode] = useState('');
  const [toolType, setToolType] = useState<'written' | 'practical' | 'rubric'>('written');
  const [generatedTool, setGeneratedTool] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [isApiConfigured, setIsApiConfigured] = useState(false);

  useEffect(() => {
    const keyIsAvailable = typeof process !== 'undefined' &&
                           typeof process.env !== 'undefined' &&
                           !!process.env.API_KEY &&
                           process.env.API_KEY.trim() !== '';
    setIsApiConfigured(keyIsAvailable);
  }, []);

  const handleGenerateTool = async () => {
    if (!isApiConfigured || !unitTitle) {
      setError('Please provide a Unit Title and ensure API is configured.');
      return;
    }

    setIsLoading(true);
    setError('');

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    try {
      const systemInstruction = `You are a TVET CDACC Assessment Expert. Generate a professional ${toolType} assessment tool in HTML format.
      DO NOT use markdown blocks. Return ONLY HTML.
      Use professional tables with solid borders (border="1").
      
      If toolType is 'written': Generate a 20-question multiple choice and short answer test.
      If toolType is 'practical': Generate a detailed observation checklist with performance criteria.
      If toolType is 'rubric': Generate a comprehensive scoring rubric with levels (Excellent, Good, Fair, Poor).`;

      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: `Generate a ${toolType} assessment tool for the unit: ${unitTitle} (${unitCode}). Ensure it follows CDACC standards.`,
        config: { systemInstruction }
      });

      const html = response.text || '';
      setGeneratedTool(`
        <div style="font-family: 'Inter', sans-serif; padding: 40px; color: #1e293b; line-height: 1.6;">
          <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px;">
            <img 
              src="https://lh3.googleusercontent.com/d/1SjQv4bgCcCO11gebydnHsnK8f1fnE0zl" 
              alt="Smart TVET Systems Logo" 
              style="max-height: 60px; width: auto; display: inline-block; margin-bottom: 15px;" 
              referrerPolicy="no-referrer"
            />
            <h1 style="font-size: 24px; font-weight: 800; text-transform: uppercase; margin: 0; color: #0f172a;">Assessment Tool: ${toolType.toUpperCase()}</h1>
            <p style="font-size: 14px; color: #64748b; margin-top: 5px; font-weight: 600;">SMART TVET SYSTEMS - QUALITY ASSURANCE</p>
          </div>
          
          <div style="background-color: #f8fafc; padding: 20px; border-radius: 12px; margin-bottom: 30px; border: 1px solid #e2e8f0;">
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 8px 0; font-weight: 700; color: #64748b; width: 120px; font-size: 12px; text-transform: uppercase;">Unit Title:</td>
                <td style="padding: 8px 0; font-weight: 800; color: #0f172a; font-size: 16px;">${unitTitle}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-weight: 700; color: #64748b; width: 120px; font-size: 12px; text-transform: uppercase;">Unit Code:</td>
                <td style="padding: 8px 0; font-weight: 800; color: #0f172a; font-size: 16px;">${unitCode || 'N/A'}</td>
              </tr>
            </table>
          </div>

          <div style="margin-top: 20px;">
            ${html}
          </div>

          <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 10px; color: #94a3b8; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;">
            Generated by Smart TVET Systems AI • Professional Assessment Series
          </div>
        </div>
      `);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Error generating tool.");
    } finally {
      setIsLoading(false);
    }
  };

  const executeDownload = (html: string, titleSuffix: string) => {
    if (!html) return;
    const fileName = `${(unitTitle || 'Assessment').replace(/ /g, '_')}_${titleSuffix}.docx`;

    const sourceHTML = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <style>
          @page { size: A4 portrait; margin: 0.5in; }
          body { font-family: 'Arial', sans-serif; font-size: 10pt; color: #333; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 15pt; border: 1pt solid #000; }
          th, td { border: 1pt solid #000; padding: 8pt; vertical-align: top; }
          h1, h2, h3 { color: #000; }
        </style>
      </head>
      <body>${html}</body>
      </html>`;
    
    const blob = new Blob([sourceHTML], { type: 'application/msword' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = fileName;
    link.click();
  };

  const handleDownload = () => {
    if (!generatedTool) return;
    executeDownload(generatedTool, `Assessment_${toolType}`);
  };

  return (
    <div className="flex h-[calc(100vh-64px)] overflow-hidden bg-slate-50">
      <aside className="w-80 bg-white border-r border-slate-200 flex flex-col shrink-0 overflow-y-auto shadow-sm z-10">
        <div className="p-8 border-b border-slate-100 bg-slate-50/50">
          <div className="w-12 h-12 bg-indigo-600 rounded-2xl flex items-center justify-center mb-4 shadow-lg shadow-indigo-100">
            <ClipboardCheck className="w-6 h-6 text-white" />
          </div>
          <h2 className="text-xl font-black text-slate-900 font-display tracking-tight">
            Assessors Tool
          </h2>
          <p className="text-xs font-bold text-slate-400 mt-1 uppercase tracking-widest">CDACC Standard Tools</p>
        </div>

        <div className="p-8 space-y-8">
          <div className="space-y-3">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest ml-1">Unit Title</label>
            <input 
              type="text" 
              value={unitTitle}
              onChange={(e) => setUnitTitle(e.target.value)}
              placeholder="e.g. Apply Plumbing Principles"
              className="w-full px-5 py-3 bg-slate-50 border border-slate-100 rounded-2xl focus:ring-4 focus:ring-indigo-500/10 focus:bg-white focus:border-indigo-500 outline-none text-sm font-medium transition-all"
            />
          </div>

          <div className="space-y-3">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest ml-1">Unit Code</label>
            <input 
              type="text" 
              value={unitCode}
              onChange={(e) => setUnitCode(e.target.value)}
              placeholder="e.g. CON/OS/PL/CR/01/6"
              className="w-full px-5 py-3 bg-slate-50 border border-slate-100 rounded-2xl focus:ring-4 focus:ring-indigo-500/10 focus:bg-white focus:border-indigo-500 outline-none text-sm font-medium transition-all"
            />
          </div>

          <div className="space-y-3">
            <label className="text-xs font-bold text-slate-400 uppercase tracking-widest ml-1">Tool Type</label>
            <div className="grid grid-cols-1 gap-3">
              {(['written', 'practical', 'rubric'] as const).map((type) => (
                <button
                  key={type}
                  onClick={() => setToolType(type)}
                  className={cn(
                    "px-5 py-3 rounded-2xl text-sm font-bold transition-all text-left capitalize flex items-center justify-between group",
                    toolType === type 
                      ? "bg-indigo-600 text-white shadow-xl shadow-indigo-100" 
                      : "bg-slate-50 text-slate-600 hover:bg-slate-100 border border-transparent hover:border-slate-200"
                  )}
                >
                  {type} Test
                  <ChevronRight className={cn("w-4 h-4 transition-transform", toolType === type ? "translate-x-0" : "-translate-x-2 opacity-0 group-hover:opacity-100 group-hover:translate-x-0")} />
                </button>
              ))}
            </div>
          </div>

          <div className="pt-4">
            <button 
              onClick={handleGenerateTool}
              disabled={isLoading || !isApiConfigured}
              className="btn-primary w-full py-4 text-sm shadow-xl shadow-indigo-100 disabled:opacity-50"
            >
              {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
              Generate Tool
            </button>
          </div>
        </div>

        <div className="mt-auto p-8 border-t border-slate-50">
          <div className="bg-amber-50 rounded-2xl p-4 border border-amber-100">
            <div className="flex items-center gap-2 text-amber-700 mb-2">
              <ShieldCheck className="w-4 h-4" />
              <span className="text-[10px] font-black uppercase tracking-widest">CDACC Compliant</span>
            </div>
            <p className="text-[10px] text-amber-600 font-medium leading-relaxed">
              All generated tools follow the official TVET CDACC assessment guidelines.
            </p>
          </div>
        </div>
      </aside>

      <main className="flex-grow flex flex-col overflow-hidden relative">
        <div className="h-20 bg-white border-b border-slate-100 flex items-center justify-between px-10 shrink-0 z-10">
          <div className="flex items-center gap-4">
            <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse" />
            <h2 className="font-black text-slate-900 font-display tracking-tight">Document Preview</h2>
          </div>
          <div className="flex items-center gap-4">
            <button 
              onClick={handleDownload}
              disabled={!generatedTool}
              className="btn-primary py-2 px-6 text-xs shadow-lg shadow-indigo-100 disabled:opacity-30"
            >
              <Download className="w-4 h-4" />
              Export Word
            </button>
          </div>
        </div>

        <div className="flex-grow overflow-auto p-12 bg-slate-100/80 flex flex-col items-center custom-scrollbar">
          <AnimatePresence>
            {error && (
              <motion.div 
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                className="mb-8 p-5 bg-rose-50 border border-rose-100 rounded-[1.5rem] flex items-start gap-4 text-rose-600 text-sm w-full max-w-3xl shadow-xl shadow-rose-100/50"
              >
                <AlertCircle className="w-6 h-6 shrink-0" />
                <div className="flex-grow font-medium">{error}</div>
                <button onClick={() => setError('')} className="p-1 hover:bg-rose-100 rounded-xl transition-colors">
                  <X className="w-5 h-5" />
                </button>
              </motion.div>
            )}
          </AnimatePresence>

          <AnimatePresence mode="wait">
            {isLoading ? (
              <motion.div 
                key="loading"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex flex-col items-center justify-center h-full text-center"
              >
                <div className="relative mb-8">
                  <div className="w-20 h-20 border-4 border-indigo-100 border-t-indigo-600 rounded-full animate-spin" />
                  <Sparkles className="w-8 h-8 text-indigo-600 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-pulse" />
                </div>
                <h3 className="text-2xl font-black text-slate-900 mb-3 font-display">Crafting Your Tool</h3>
                <p className="text-slate-500 text-sm max-w-xs font-medium leading-relaxed">Our AI is analyzing CDACC standards to generate a professional assessment tool for you.</p>
              </motion.div>
            ) : !generatedTool ? (
              <motion.div 
                key="empty"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="flex flex-col items-center justify-center h-full text-center max-w-md"
              >
                <div className="w-24 h-24 bg-white rounded-[2.5rem] flex items-center justify-center shadow-2xl border border-slate-100 mb-10 relative group">
                  <div className="absolute inset-0 bg-indigo-600 rounded-[2.5rem] opacity-0 group-hover:opacity-10 transition-opacity blur-xl"></div>
                  <ClipboardCheck className="w-12 h-12 text-slate-200 group-hover:text-indigo-600 transition-colors" />
                </div>
                <h3 className="text-3xl font-black text-slate-900 mb-4 font-display tracking-tight">Ready to Generate?</h3>
                <p className="text-slate-500 text-base leading-relaxed mb-10 font-medium">
                  Enter your unit details in the sidebar and select the type of assessment tool you need. We'll handle the rest.
                </p>
                <div className="flex items-center gap-6 text-slate-400">
                   <div className="flex items-center gap-2">
                     <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                     <span className="text-xs font-bold uppercase tracking-widest">Written</span>
                   </div>
                   <div className="flex items-center gap-2">
                     <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                     <span className="text-xs font-bold uppercase tracking-widest">Practical</span>
                   </div>
                   <div className="flex items-center gap-2">
                     <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                     <span className="text-xs font-bold uppercase tracking-widest">Rubrics</span>
                   </div>
                </div>
              </motion.div>
            ) : (
              <motion.div 
                key="content"
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-white shadow-[0_32px_64px_-12px_rgba(0,0,0,0.14)] border border-slate-200 w-[8.27in] min-h-[11.69in] p-[0.75in] rounded-sm mb-20 relative"
              >
                <div className="absolute top-0 left-0 w-full h-1 bg-indigo-600" />
                <div 
                  className="prose prose-slate max-w-none prose-headings:font-display prose-headings:font-black prose-p:font-medium prose-table:border-collapse prose-td:border prose-td:border-slate-300 prose-th:bg-slate-50 prose-th:border prose-th:border-slate-300"
                  dangerouslySetInnerHTML={{ __html: generatedTool }} 
                />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>
    </div>
  );
};

export default AssessorsTool;
